version: '3.8'

services:
  web:
    image: bethuel-portfolio:latest
    container_name: bethuel-portfolio
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,web,0.0.0.0,*
      - DJANGO_SECRET_KEY=your-secret-key-here
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
    command: gunicorn --bind 0.0.0.0:8000 portfolio.wsgi:application
